module.exports = [
    'The Dark Knight ',
    'Inception',
    'The Matrix',
    'Gladiator ',
    'Raiders of the Lost Ark',
    'Terminator 2',
    'The Dark Knight Rises',
    'Aliens',
    'North by Northwest',
    'Batman Begins',
    'Indiana Jones and the Last Crusade',
    'V for Vendetta ',
    'Die Hard',
    'Dunkirk',
    'Logan',
    'Guardians of the Galaxy',
    'The Avengers',
    'Kill Bill: Vol. 1',
    'Rush',
    'Thor: Ragnarok',
    'The Incredibles',
    'Star Trek',
    'The Terminator',
    'Casino Royale',
    'The Wild Bunch',
    'High Noon',
    'The Iron Giant',
    'Edge of Tomorrow',
    'The Boondock Saints',
    'Hard Boiled',
    'Captain America: Civil War',
    'Avatar',
    'The Last of the Mohicans',
    'Taken',
    'Predator',
    'Tombstone',
    'The Lego Movie',
    'Star Trek: Into Darkness',
    'The Fugitive',
    'The Count of Monte Cristo',
    'The Magnificent Seven',
    'Dirty Harry',
    'Goldfinger',
    'The French Connection',
    'Baby Driver',
    'The Fifth Element',
    '300',
    'First Blood',
    'Setup',
    'The Next Karate Kid',
    'Driven',
    'The Marine',
    'Jonah Hex',
    'Fire Down Below',
    'Get Carter',
    '10,000 BC',
    'The Glimmer Man',
    'Max Payne',
    'Volcano',
    'Snakes on a Plane',
    'Nowhere to Run',
    'The Delta Force',
    'Poseidon',
    'Domino',
    'Point of No Return',
    'The Doom Generation',
    'Kidnap',
    'Days of Thunder',
    'The Net',
    'The Substitute',
    'Noah',
    'Daylight',
    'The Fan',
    'Over the Top',
    'Alexander',
    'San Andreas',
    'Pearl Harbor ',
    'Deep Impact',
    'Eraser',
    'A Man Apart',
    'Antitrust',
    'Above the Law',
    'Hancock',
    'The Perfect Storm',
    'Miami Connection',
    'Last Man Standing',
    'Blue Thunder',
    'Twister',
    'Blind Fury',
    'Colossal',
    'The Bodyguard',
    'Elysium',
    'The Prophecy',
    'Judgment Night',
    'Snitch',
    'Flyboys',
    '48 Hrs.',
    'Enemy Mine',
    'Dead Presidents',
    'Chappie',
    'The Grey',
    'Bad Boys',
    'Young Guns',
    'Back to the Future',
    'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    'Snatch',
    'Toy Story',
    'Up',
    'Some Like It Hot',
    'The Wolf of Wall Street',
    'The Big Lebowski',
    'The Truman Show',
    'Finding Nemo',
    'Hot Fuzz',
    'The Artist',
    'Do the Right Thing',
    'Ed Wood',
    'The Goonies',
    "Ferris Bueller's Day Off",
    'Silver Linings Playbook',
    'Moonrise Kingdom',
    'Ghostbusters',
    'Airplane!',
    'Blazing Saddles',
    'Office Space',
    'Tusk',
    'Shocker',
    "Freddy's Dead: The Final Nightmare",
    'Leprechaun',
    'Attack of the Killer Tomatoes!',
    'Troll 2',
    'Split',
    'Sicario',
    'Mad Max: Fury Road',
    'Fargo',
    'The Mummy',
    'Arrival',
    'The Godfather',
    'Logan Lucky',
    'Pulp Fiction',
    'Drive',
    'Cloverfield',
    'The Thing',
    'The Mist',
    'King Kong',
    'They Live',
    'Event Horizon',
    'The Fly',
    'Alien 3',
    'Leviathan',
    'Predator 2',
    'Hollow Man',
    'The Wraith',
    'Pi',
    'Dreamcatcher',
    'Teen Wolf',
    'Pitch Perfect',
    'Bridesmaids',
    'Clueless ',
    'Weird Science',
    'Inherent Vice',
    '500 Days of Summer',
    'Easy A',
    'Secretary',
    'Midnight in Paris',
    'Coming to America',
    'Swiss Army Man',
    'Good Time',
    'A Ghost Story',
    'Free Fire',
    'Atomic Blonde',
    'Annihilation',
    'Star Wars: Episode IV - A New Hope',
];
