module.exports = [
    'Miami Connection',
    'Ghoulies',
    'Hot Pursuit',
    'The Last Airbender ',
    'Mobsters',
    'In The Army Now',
    'Cocktail',
    'The Adventures of Pluto Nash',
    'A Kid in King Arthur%27s Court',
    'Cool World',
    'Vampires Suck',
    'Problem Child',
    'Caddyshack II',
    'Delta Farce',
    'Battlefield Earth',
    'FearDotCom',
    'Getting Even with Dad',
    'Disaster Movie',
    'Daddy Day Camp',
    'Jaws: The Revenge',
    'Return to The Blue Lagoon',
    'Staying Alive',
    'Wagons East!',
    'Mac and Me',
    'Just Getting Started',
    'Rings',
    'The Emoji Movie',
    'The Mummy',
    'The Dark Tower',
    'The House',
    'Jawbreaker',
    'Chill Factor',
    'Corky Romano',
    'Ballistic: Ecks vs. Sever',
    'Twisted',
    'Alone in the Dark',
    'Basic Instinct 2',
    'The Number 23',
    'Good Luck Chuck',
    'Premonition',
    'Deck the Halls',
    'The Covenant',
    'The Perfect Man',
    'White Noise',
    'Christmas with the Kranks',
    'The Whole Ten Yards',
    'Darkness Falls',
    'Rollerball',
    'Serving Sara',
    'Glitter',
    'Jonah Hex',
    'Fire Down Below',
    'Get Carter',
    '10,000 BC',
    'The Glimmer Man',
    'Max Payne',
    'Volcano',
    'Snakes on a Plane',
    'Nowhere to Run',
    'Poseidon',
    'Point of No Return',
    'The Doom Generation',
    'Kidnap',
    'Days of Thunder',
    'The Net',
    'The Substitute',
    'The Fan',
    'Over the Top',
    'Alexander',
    'San Andreas',
    'Pearl Harbor ',
    'Eraser',
    'A Man Apart',
    'Antitrust',
    'Above the Law',
    'Hancock',
    'Last Man Standing',
    'Twister',
    'Blind Fury',
    'The Bodyguard',
    'The Prophecy',
    'Judgment Night',
    'Snitch',
    'Flyboys',
    'Enemy Mine',
    'Dead Presidents',
    'Chappie',
    'Dorian Gray',
    'Bad Boys II',
    'Young Guns II',
    'Snatched',
    'Pacific Rim Uprising',
    'Ghostbusters II',
    'Airplane II: The Sequel',
    'Tusk',
    'Shocker',
    "Freddy's Dead: The Final Nightmare",
    'Leprechaun',
    'Attack of the Killer Tomatoes!',
    'Troll 2',
    'Splitting Heirs',
    'The Mummy Returns',
    'King Kong vs. Godzilla',
    'Event Horizon',
    'The Fly II',
    'Aliens vs Predator',
    'Hollow Man',
    'The Wraith',
    'Aliens in the Attic',
    'Dreamcatcher',
    'Teen Wolf Too',
    'Pitch Perfect 3',
    'Star Wars: The Clone Wars',
    'Burlesque',
    'Halloween III - Season of the Witch',
    'Season of the Witch',
    'Old Dogs',
    'Drive Angry',
    'All About Steve',
    'Sucker Punch',
    'The Tourist',
    'The Love Guru',
    'Green Lantern',
    'The Back-up Plan',
    'The Smurfs',
    'Skyline',
    'Punisher: War Zone',
    'I Know Who Killed Me',
    'Leprechaun in the Hood',
    'Superman III',
    'Catwoman',
    'Jingle All the Way',
    'Trespass',
    'Cool as Ice',
    'Birdemic: Shock And Terror',
    '88 Minutes',
    'Abduction',
    'Tiptoes',
    'On the Line',
    'Bad Ass',
    'Judge Dredd',
    'Batman and Robin',
    'Wild Wild West',
    'Road House',
    'Barb Wire',
    'Super Mario Bros.',
    'Sleepaway Camp',
    'Cobra',
    'Reindeer Games',
    'Anaconda',
    'The Odd Life of Timothy Green',
    'Nothing but Trouble',
    'From Justin to Kelly',
    'In the Name of the King: A Dungeon Siege Tale',
    'Spice World',
    'Street Fighter',
    'Stop! Or My Mom Will Shoot',
    'Joyful Noise',
    'After Earth',
    'Howard the Duck',
    'Demolition Man',
    'Sharknado 3: Oh Hell No!',
    'Sharknado 4',
    'Sharknado 5: Global Swarming',
    'Crocodile Dundee in Los Angeles',
    'Gymkata',
    'The Glimmer Man',
    'Toys',
    'Congo',
    'Hudson Hawk',
    'Crossroads',
    'Deck the Halls',
    'Jack Frost',
    'Mortal Kombat',
    'Mortal Kombat: Annihilation',
    'Double Team',
    'Winter%27s Tale',
    'No Holds Barred',
    'Color of Night',
    'Ernest Goes to Jail',
    'Mr. Nanny',
    'Gooby',
    'Monkey Shines',
    'Rhinestone',
    'LOL',
    'A View to a Kill',
    'Junior',
    'Xanadu',
    'Tango %26 Cash',
    'liz %26 dick',
    'Zardoz',
    'Deep Blue Sea',
    'Lake Placid 2',
    'Con Air',
    'The Island of Dr. Moreau',
    'Hercules in New York',
    'Jupiter Ascending',
    'Teenage Mutant Ninja Turtles II - The Secret of the Ooze',
    'Teenage Mutant Ninja Turtles III',
    'Teenage Mutant Ninja Turtles',
    'Runaway',
    'Top Dog',
    'Maximum Overdrive',
    'Masters of the Universe',
    'Perfect',
    'Perfect Stranger',
    'Hackers',
    'Steel',
    'Kazaam',
    'Teen Witch',
    'The Covenant',
    'Bloodsport',
    'The Quest',
    'Solarbabies',
    'Hell Comes to Frogtown',
    'The Boy Next Door',
    'Simply Irresistible',
    'The Shadow',
    'The Phantom',
    'Gods of Egypt',
    'Stealth',
    'The Lawnmower Man',
    'Grease 2',
    'Escape from L.A.',
    'Highlander II: The Quickening',
    'Airborne',
    'Surf Ninjas',
    'Body Parts',
    'Sleepwalkers',
    'The Lake House',
    'My Stepmother Is an Alien',
    'Timecop',
    'Hard Ticket to Hawaii',
    'The Garbage Pail Kids Movie',
    'The Last Dragon',
    'Virtuosity',
    'Jason X',
    'Ultraviolet',
    'Valerian and the City of a Thousand Planets',
    'Superman IV: The Quest for Peace',
    'Second Sight',
    'Howling II',
    'Howling III',
    'Freejack',
    'Ladybugs',
    'Johnny Mnemonic',
    'Adore',
    'Geostorm',
    'Beautiful Creatures',
    'Dark Tide',
    'Shark Night 3D',
];
