module.exports = [
    'Miami Connection',
    'Ghoulies',
    'Hot Pursuit',
    'The Last Airbender ',
    'Gigli',
    'Mobsters',
    'In The Army Now',
    'Kazam',
    'Cocktail',
    'The Adventures of Pluto Nash',
    'A Kid in King Arthurs Court',
    'Cool World',
    'Vampires Suck',
    'Problem Child',
    'Caddyshack II',
    'Delta Farce',
    'Battlefield Earth',
    'Fear Dot Com',
    'Getting Even with Dad',
    'Disaster Movie',
    'Daddy Day Camp',
    'Jaws: The Revenge',
    'Return to The Blue Lagoon',
    'Staying Alive',
    'Wagons East!',
    'Mac and Me',
    'Just Getting Started',
    'Rings',
    'The Emoji Movie',
    'The Mummy',
    'The Dark Tower',
    'The House',
    'Jawbreaker',
    'Chill Factor',
    'Corky Romano',
    'Ballistic: Ecks vs. Sever',
    'Twisted',
    'Alone in the Dark',
    'Basic Instinct 2',
    'The Number 23',
    'Good Luck Chuck',
    'Premonition',
    'Deck the Halls',
    'The Covenant',
    'The Perfect Man',
    'White Noise',
    'Christmas with the Kranks',
    'The Whole Ten Yards',
    'Darkness Falls',
    'Roller Ball',
    'Serving Sara',
    'Glitter',
    'Jonah Hex',
    'Fire Down Below',
    'Get Carter',
    '10,000 BC',
    'The Glimmer Man',
    'Max Payne',
    'Volcano',
    'Snakes on a Plane',
    'Nowhere to Run',
    'Poseidon',
    'Domino',
    'Point of No Return',
    'The Doom Generation',
    'Kidnap',
    'Days of Thunder',
    'The Net',
    'The Substitute',
    'The Fan',
    'Over the Top',
    'Alexander',
    'San Andreas',
    'Pearl Harbor ',
    'Eraser',
    'A Man Apart',
    'Antitrust',
    'Above the Law',
    'Hancock',
    'The Perfect Storm',
    'Last Man Standing',
    'Blue Thunder',
    'Twister',
    'Blind Fury',
    'The Bodyguard',
    'The Prophecy',
    'Judgment Night',
    'Snitch',
    'Flyboys',
    'Enemy Mine',
    'Dead Presidents',
    'Chappie',
    'Dorian Gray',
    'Bad Boys II',
    'Young Guns II',
    'Snatched',
    'Pacific Rim Uprising',
    'Ghostbusters 2',
    'Airplane 2 - The Sequel',
    'Tusk',
    'Shocker',
    "Freddy's Dead: The Final Nightmare",
    'Leprechaun',
    'Attack of the Killer Tomatoes!',
    'Troll 2',
    'Splitting Heirs',
    'The Mummy Returns',
    'King Kong vs. Godzilla',
    'Event Horizon',
    'The Fly II',
    'Aliens vs. Predator: Requiem (AVP 2)',
    'Leviathan',
    'Hollow Man',
    'The Wraith',
    'Aliens in the Attic',
    'Dreamcatcher',
    'Teen Wolf Too',
    'Pitch Perfect 3',
    'Star Wars: The Clone Wars',
];
